name: future_of_workout
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.4
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/body/back/
    - assets/body/front/
    - assets/exercises/barbel_bench_press/
    - assets/exercises/squat/
    - assets/exercises/deadlift/
