name: future_of_workout
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  body_api:
    path: packages/body_api
  equatable: ^2.0.5
  exercise_repository:
    path: packages/exercise_repository
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.4
  go_router: ^4.3.0
  goal_repository:
    path: packages/goal_repository
  google_fonts: ^3.0.1
  intl: ^0.17.0
  local_storage_exercise_api:
    path: packages/local_storage_exercise_api
  local_storage_goal_api:
    path: packages/local_storage_goal_api
  local_storage_measurement_api:
    path: packages/local_storage_measurement_api
  local_storage_workout_api:
    path: packages/local_storage_workout_api
  local_storage_workout_log_api:
    path: packages/local_storage_workout_log_api
  logger: ^1.1.0
  measurement_repository:
    path: packages/measurement_repository
  uuid: ^3.0.6
  workout_log_repository:
    path: packages/workout_log_repository
  workout_repository:
    path: packages/workout_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/body/back/
    - assets/body/front/
    - assets/exercises/barbel_bench_press/
    - assets/exercises/squat/
    - assets/exercises/deadlift/
