name: future_of_workout
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  exercise_api:
    path: packages/exercise_api
  exercise_repository:
    path: packages/exercise_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.4
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  local_storage_exercise_api:
    path: packages/local_storage_exercise_api
  local_storage_workout_api:
    path: packages/local_storage_workout_api
  local_storage_workout_log_api:
    path: packages/local_storage_workout_log_api
  logger: ^1.1.0
  uuid: ^3.0.6
  workout_api:
    path: packages/workout_api
  workout_log_api:
    path: packages/workout_log_api
  workout_log_repository:
    path: packages/workout_log_repository
  workout_repository:
    path: packages/workout_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/body/back/
    - assets/body/front/
    - assets/exercises/barbel_bench_press/
    - assets/exercises/squat/
    - assets/exercises/deadlift/
