name: local_storage_exercise_api
description: A Flutter implementation of the ExerciseApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  exercise_api:
    path: ../exercise_api
  hive_flutter: ^1.1.0
  meta: ^1.3.0
  rxdart: ^0.27.2

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
