name: local_storage_workout_api
description: Flutter implementation of the WorkoutApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive_flutter: ^1.1.0
  meta: ^1.3.0
  rxdart: ^0.27.5
  workout_api:
    path: ../workout_api

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
