name: exercise_repository
description: A repository that handles exercise related requests.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  exercise_api:
    path: ../exercise_api
  meta: ^1.3.0
  rxdart: ^0.27.2
  
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
